import React from 'react';
import {
  Brush,
  HeartHandshake,
  Mic,
  Gamepad2,
  Camera,
  Plane,
  ClipboardList,
  Dumbbell,
  Book,
  Languages,
  Bike,
  FlaskConical,
  PenTool,
  Brain,
  GraduationCap,
  Music,
  Film,
  Flower,
  Cat,
  Users,
//   Bulb,
  Cog,
  Cpu,
  Pencil,
  Building,
  Landmark,
  Leaf,
  Rat,
  Atom,
  Calculator,
  BarChart,
  Users2,
  Globe,
  HeartPulse,
  Clock,
  Beaker,
  PieChart,
  Microscope,
  Palette,
  Edit,
  Scissors,
  BookOpen,
  PencilRuler,
  MessageCircle,
  Star,
  BookMarked,
  Flag,
  Languages as LangIcon,
//   PuzzlePiece,
  Activity,
//   Yoga,
//   WrenchScrewdriver,
  Stethoscope,
//   PillInactive,
  Scroll,
  Video,
  ShoppingBag,
  Headphones,
  Briefcase,
  GraduationCap as CourseIcon
} from 'lucide-react';

const interests = [
  {
    id: "drawing",
    title: "Drawing",
    description: "Sketching, shading, and digital illustration.",
    icon: <Brush className="h-6 w-6" />,
    color: "bg-pink-500",
  },
  {
    id: "dancing",
    title: "Dancing",
    description: "Express through classical, modern, or freestyle dance.",
    icon: <HeartHandshake className="h-6 w-6" />,
    color: "bg-red-400",
  },
  {
    id: "singing",
    title: "Singing",
    description: "Vocal performance across genres and languages.",
    icon: <Mic className="h-6 w-6" />,
    color: "bg-yellow-500",
  },
  {
    id: "sports",
    title: "Sports",
    description: "Competitive physical activities and team games.",
    icon: <Activity className="h-6 w-6" />,
    color: "bg-emerald-500",
  },
  {
    id: "video-games",
    title: "Video Games",
    description: "Immersive digital experiences and interactive fun.",
    icon: <Gamepad2 className="h-6 w-6" />,
    color: "bg-indigo-500",
  },
  {
    id: "acting",
    title: "Acting",
    description: "Performance art through theater, film, or television.",
    icon: <Film className="h-6 w-6" />,
    color: "bg-purple-500",
  },
  {
    id: "traveling",
    title: "Travelling",
    description: "Exploring new places, cultures, and adventures.",
    icon: <Plane className="h-6 w-6" />,
    color: "bg-teal-500",
  },
  {
    id: "gardening",
    title: "Gardening",
    description: "Growing and nurturing plants and outdoor spaces.",
    icon: <Flower className="h-6 w-6" />,
    color: "bg-green-500",
  },
  {
    id: "animals",
    title: "Animals",
    description: "Caring for and learning about different animal species.",
    icon: <Cat className="h-6 w-6" />,
    color: "bg-amber-500",
  },
  {
    id: "photography",
    title: "Photography",
    description: "Capturing the world through your lens.",
    icon: <Camera className="h-6 w-6" />,
    color: "bg-blue-500",
  },
  {
    id: "teaching",
    title: "Teaching",
    description: "Sharing knowledge and helping others learn.",
    icon: <Users className="h-6 w-6" />,
    color: "bg-sky-600",
  },
  {
    id: "exercise",
    title: "Exercise",
    description: "Fitness, workouts, and healthy routines.",
    icon: <Dumbbell className="h-6 w-6" />,
    color: "bg-green-600",
  },
  {
    id: "coding",
    title: "Coding",
    description: "Creating software, solving problems, building apps.",
    icon: <ClipboardList className="h-6 w-6" />,
    color: "bg-violet-500",
  },
  {
    id: "electricity-components",
    title: "Electricity Components",
    description: "Working with circuits, electronics, and electrical systems.",
    // icon: <Bulb className="h-6 w-6" />,
    color: "bg-amber-400",
  },
  {
    id: "mechanic-parts",
    title: "Mechanic Parts",
    description: "Building, repairing, and understanding mechanical systems.",
    icon: <Cog className="h-6 w-6" />,
    color: "bg-slate-600",
  },
  {
    id: "computer-parts",
    title: "Computer Parts",
    description: "Hardware components and system building.",
    icon: <Cpu className="h-6 w-6" />,
    color: "bg-blue-600",
  },
  {
    id: "research",
    title: "Researching",
    description: "In-depth exploration and investigation.",
    icon: <Brain className="h-6 w-6" />,
    color: "bg-sky-500",
  },
  {
    id: "architecture",
    title: "Architecture",
    description: "Designing structures and understanding built environments.",
    icon: <Building className="h-6 w-6" />,
    color: "bg-stone-600",
  },
  {
    id: "historic-collection",
    title: "Historic Collection",
    description: "Collecting and preserving items of historical significance.",
    icon: <Landmark className="h-6 w-6" />,
    color: "bg-amber-700",
  },
  {
    id: "botany",
    title: "Botany",
    description: "The study of plants and their biology.",
    icon: <Leaf className="h-6 w-6" />,
    color: "bg-lime-600",
  },
  {
    id: "zoology",
    title: "Zoology",
    description: "The study of animals and animal life.",
    icon: <Rat className="h-6 w-6" />,
    color: "bg-orange-600",
  },
  {
    id: "physics",
    title: "Physics",
    description: "Understanding the fundamental laws of nature.",
    icon: <Atom className="h-6 w-6" />,
    color: "bg-blue-700",
  },
  {
    id: "accounting",
    title: "Accounting",
    description: "Financial record-keeping and analysis.",
    icon: <Calculator className="h-6 w-6" />,
    color: "bg-cyan-700",
  },
  {
    id: "economics",
    title: "Economics",
    description: "The study of resources, wealth, and financial systems.",
    icon: <BarChart className="h-6 w-6" />,
    color: "bg-emerald-700",
  },
  {
    id: "sociology",
    title: "Sociology",
    description: "The study of society and social relationships.",
    icon: <Users2 className="h-6 w-6" />,
    color: "bg-indigo-600",
  },
  {
    id: "geography",
    title: "Geography",
    description: "The study of places and the relationships between people and their environments.",
    icon: <Globe className="h-6 w-6" />,
    color: "bg-teal-700",
  },
  {
    id: "psychology",
    title: "Psychology",
    description: "The scientific study of the mind and behavior.",
    icon: <HeartPulse className="h-6 w-6" />,
    color: "bg-rose-600",
  },
  {
    id: "history",
    title: "History",
    description: "Study of past events and human affairs.",
    icon: <Clock className="h-6 w-6" />,
    color: "bg-amber-800",
  },
  {
    id: "science",
    title: "Science",
    description: "Discovering how the world works.",
    icon: <FlaskConical className="h-6 w-6" />,
    color: "bg-cyan-600",
  },
  {
    id: "business-education",
    title: "Business Education",
    description: "Learning about commerce, management, and entrepreneurship.",
    icon: <PieChart className="h-6 w-6" />,
    color: "bg-blue-800",
  },
  {
    id: "chemistry",
    title: "Chemistry",
    description: "The study of substances, their properties, and reactions.",
    icon: <Beaker className="h-6 w-6" />,
    color: "bg-purple-700",
  },
  {
    id: "mathematics",
    title: "Mathematics",
    description: "The abstract science of numbers, quantity, and space.",
    icon: <PieChart className="h-6 w-6" />,
    color: "bg-indigo-700",
  },
  {
    id: "biology",
    title: "Biology",
    description: "The study of living organisms and life processes.",
    icon: <Microscope className="h-6 w-6" />,
    color: "bg-green-700",
  },
  {
    id: "makeup",
    title: "Makeup",
    description: "Artistic application of cosmetics for beauty or transformation.",
    icon: <Palette className="h-6 w-6" />,
    color: "bg-pink-600",
  },
  {
    id: "designing",
    title: "Designing",
    description: "Creative work in fashion, graphics, or UI/UX.",
    icon: <PenTool className="h-6 w-6" />,
    color: "bg-fuchsia-500",
  },
  {
    id: "content-writing",
    title: "Content Writing",
    description: "Creating written material for various platforms.",
    icon: <Edit className="h-6 w-6" />,
    color: "bg-violet-600",
  },
  {
    id: "crafting",
    title: "Crafting",
    description: "Creating handmade items and art projects.",
    icon: <Scissors className="h-6 w-6" />,
    color: "bg-rose-500",
  },
  {
    id: "literature",
    title: "Literature",
    description: "Appreciation and study of written works of artistic merit.",
    icon: <BookOpen className="h-6 w-6" />,
    color: "bg-amber-600",
  },
  {
    id: "reading",
    title: "Reading",
    description: "Enjoying books, literature, and learning.",
    icon: <Book className="h-6 w-6" />,
    color: "bg-orange-500",
  },
  {
    id: "cartooning",
    title: "Cartooning",
    description: "Creating illustrated comics and animated characters.",
    icon: <PencilRuler className="h-6 w-6" />,
    color: "bg-yellow-600",
  },
  {
    id: "debating",
    title: "Debating",
    description: "Formal discussion and argumentation on important topics.",
    icon: <MessageCircle className="h-6 w-6" />,
    color: "bg-blue-600",
  },
  {
    id: "astrology",
    title: "Astrology",
    description: "Study of celestial bodies' influence on human affairs.",
    icon: <Star className="h-6 w-6" />,
    color: "bg-indigo-600",
  },
  {
    id: "hindi",
    title: "Hindi",
    description: "Speaking, reading, or studying the Hindi language.",
    icon: <BookMarked className="h-6 w-6" />,
    color: "bg-orange-600",
  },
  {
    id: "french",
    title: "French",
    description: "Speaking, reading, or studying the French language.",
    icon: <Flag className="h-6 w-6" />,
    color: "bg-blue-700",
  },
  {
    id: "english",
    title: "English",
    description: "Speaking, reading, or studying the English language.",
    icon: <BookMarked className="h-6 w-6" />,
    color: "bg-red-700",
  },
  {
    id: "urdu",
    title: "Urdu",
    description: "Speaking, reading, or studying the Urdu language.",
    icon: <BookMarked className="h-6 w-6" />,
    color: "bg-green-800",
  },
  {
    id: "other-language",
    title: "Other Language",
    description: "Speaking, reading, or studying various other languages.",
    icon: <LangIcon className="h-6 w-6" />,
    color: "bg-rose-500",
  },
  {
    id: "solving-puzzles",
    title: "Solving Puzzles",
    description: "Tackling brain teasers, riddles, and logical challenges.",
    // icon: <PuzzlePiece className="h-6 w-6" />,
    color: "bg-amber-500",
  },
  {
    id: "gymnastics",
    title: "Gymnastics",
    description: "Athletic exercises developing physical strength and coordination.",
    icon: <Activity className="h-6 w-6" />,
    color: "bg-red-500",
  },
  {
    id: "yoga",
    title: "Yoga",
    description: "Physical, mental, and spiritual practices for holistic health.",
    // icon: <Yoga className="h-6 w-6" />,
    color: "bg-teal-600",
  },
  {
    id: "engineering",
    title: "Engineering",
    description: "Designing and building structures, machines, and systems.",
    // icon: <WrenchScrewdriver className="h-6 w-6" />,
    color: "bg-blue-800",
  },
  {
    id: "doctor",
    title: "Doctor",
    description: "Medicine and healthcare professionals.",
    icon: <Stethoscope className="h-6 w-6" />,
    color: "bg-red-600",
  },
  {
    id: "pharmacist",
    title: "Pharmacist",
    description: "Preparation and dispensing of medicinal drugs.",
    // icon: <PillInactive className="h-6 w-6" />,
    color: "bg-green-700",
  },
  {
    id: "cycling",
    title: "Cycling",
    description: "Outdoor adventure and fitness on two wheels.",
    icon: <Bike className="h-6 w-6" />,
    color: "bg-lime-500",
  },
  {
    id: "knitting",
    title: "Knitting",
    description: "Creating fabric by interlocking yarn using needles.",
    icon: <Scissors className="h-6 w-6" />,
    color: "bg-pink-700",
  },
  {
    id: "director",
    title: "Director",
    description: "Leading creative projects in film, theater, or other media.",
    icon: <Video className="h-6 w-6" />,
    color: "bg-purple-700",
  },
  {
    id: "journalism",
    title: "Journalism",
    description: "Reporting, writing, and sharing stories.",
    icon: <Scroll className="h-6 w-6" />,
    color: "bg-gray-600",
  },
  {
    id: "business",
    title: "Business",
    description: "Commercial activities, entrepreneurship, and management.",
    icon: <ShoppingBag className="h-6 w-6" />,
    color: "bg-blue-600",
  },
  {
    id: "listening-music",
    title: "Listening Music",
    description: "Enjoying various genres and forms of musical expression.",
    icon: <Headphones className="h-6 w-6" />,
    color: "bg-purple-600",
  },
  {
    id: "courses",
    title: "Courses",
    description: "Pursuing educational programs and learning opportunities.",
    icon: <Briefcase className="h-6 w-6" />,
    color: "bg-sky-600",
  },
  {
    id: "languages",
    title: "Languages",
    description: "Learning and mastering new languages.",
    icon: <Languages className="h-6 w-6" />,
    color: "bg-rose-500",
  },
];

export default interests;