const degreeStreamList = [
    // Engineering
    { typeOfCollege: "engineering", stream: "b.tech - bachelor of technology" },
    { typeOfCollege: "engineering", stream: "m.tech - master of technology" },
    { typeOfCollege: "engineering", stream: "b.e - bachelor of engineering" },
    { typeOfCollege: "engineering", stream: "m.e - master of engineering" },
    { typeOfCollege: "engineering", stream: "diploma" },
    { typeOfCollege: "engineering", stream: "polytechnic" },
  
    // Medical
    { typeOfCollege: "medical", stream: "mbbs - bachelor of medicine, bachelor of surgery" },
    { typeOfCollege: "medical", stream: "bds - bachelor of dental surgery" },
    { typeOfCollege: "medical", stream: "bams - bachelor of ayurveda, medicine and surgery" },
    { typeOfCollege: "medical", stream: "bhms - bachelor of homeopathic medicine and surgery" },
    { typeOfCollege: "medical", stream: "bums - bachelor of unani medicine and surgery" },
    { typeOfCollege: "medical", stream: "bpt - bachelor of physiotherapy" },
    { typeOfCollege: "medical", stream: "mpt - master of physiotherapy" },
    { typeOfCollege: "medical", stream: "b.sc nursing - bachelor of science in nursing" },
    { typeOfCollege: "medical", stream: "m.sc nursing - master of science in nursing" },
    { typeOfCollege: "medical", stream: "b.pharm - bachelor of pharmacy" },
    { typeOfCollege: "medical", stream: "m.pharm - master of pharmacy" },
    { typeOfCollege: "medical", stream: "d.pharm - diploma in pharmacy" },
    { typeOfCollege: "medical", stream: "bmlt - bachelor of medical laboratory technology" },
    { typeOfCollege: "medical", stream: "b.sc radiology - bachelor of science in radiology" },
    { typeOfCollege: "medical", stream: "b.sc biotechnology - bachelor of science in biotechnology" },
    { typeOfCollege: "medical", stream: "b.sc microbiology - bachelor of science in microbiology" },
    { typeOfCollege: "medical", stream: "b.sc anesthesia - bachelor of science in anesthesia" },
    { typeOfCollege: "medical", stream: "b.sc optometry - bachelor of science in optometry" },
  
    // Computer
    { typeOfCollege: "computer", stream: "bca - bachelor of computer applications" },
    { typeOfCollege: "computer", stream: "mca - master of computer applications" },
  
    // Science
    { typeOfCollege: "science", stream: "b.sc mathematics - bachelor of science in mathematics" },
    { typeOfCollege: "science", stream: "m.sc mathematics - master of science in mathematics" },
    { typeOfCollege: "science", stream: "b.sc physics - bachelor of science in physics" },
    { typeOfCollege: "science", stream: "m.sc physics - master of science in physics" },
    { typeOfCollege: "science", stream: "b.sc chemistry - bachelor of science in chemistry" },
    { typeOfCollege: "science", stream: "m.sc chemistry - master of science in chemistry" },
    { typeOfCollege: "science", stream: "b.sc zoology - bachelor of science in zoology" },
    { typeOfCollege: "science", stream: "b.sc botany - bachelor of science in botany" },
  
    // Management
    { typeOfCollege: "management", stream: "bba - bachelor of business administration" },
    { typeOfCollege: "management", stream: "mba - master of business administration" },
  
    // Law
    { typeOfCollege: "law", stream: "llb - bachelor of laws" },
    { typeOfCollege: "law", stream: "llm - master of laws" },
    { typeOfCollege: "law", stream: "ba llb - bachelor of arts and bachelor of laws" },
    { typeOfCollege: "law", stream: "bba llb - bachelor of business administration and bachelor of laws" },
  
    // Arts
    { typeOfCollege: "arts", stream: "ba - bachelor of arts" },
    { typeOfCollege: "arts", stream: "ma - master of arts" },
    { typeOfCollege: "arts", stream: "bfa - bachelor of fine arts" },
    { typeOfCollege: "arts", stream: "mfa - master of fine arts" },
    { typeOfCollege: "arts", stream: "bpa - bachelor of performing arts" },
    { typeOfCollege: "arts", stream: "mpa - master of performing arts" }
  ];
  

  const collegeData = [
    { typeOfCollege: "engineering", course: "computer science" },
    { typeOfCollege: "engineering", course: "information technology" },
    { typeOfCollege: "engineering", course: "software engineering" },
    { typeOfCollege: "engineering", course: "data science" },
    { typeOfCollege: "engineering", course: "artificial intelligence" },
    { typeOfCollege: "engineering", course: "cybersecurity" },
    { typeOfCollege: "science", course: "physics" },
    { typeOfCollege: "science", course: "mathematics" },
    { typeOfCollege: "science", course: "biology" },
    { typeOfCollege: "science", course: "chemistry" },
    { typeOfCollege: "science", course: "environmental science" },
    { typeOfCollege: "science", course: "astronomy" },
    { typeOfCollege: "engineering", course: "mechanical engineering" },
    { typeOfCollege: "engineering", course: "civil engineering" },
    { typeOfCollege: "engineering", course: "electrical engineering" },
    { typeOfCollege: "engineering", course: "electronics & communication engineering" },
    { typeOfCollege: "engineering", course: "chemical engineering" },
    { typeOfCollege: "engineering", course: "biomedical engineering" },
    { typeOfCollege: "engineering", course: "aerospace engineering" },
    { typeOfCollege: "engineering", course: "automobile engineering" },
    { typeOfCollege: "management", course: "business administration" },
    { typeOfCollege: "management", course: "marketing" },
    { typeOfCollege: "management", course: "finance" },
    { typeOfCollege: "management", course: "economics" },
    { typeOfCollege: "management", course: "accounting" },
    { typeOfCollege: "management", course: "entrepreneurship" },
    { typeOfCollege: "management", course: "supply chain management" },
    { typeOfCollege: "management", course: "human resource management" },
    { typeOfCollege: "arts", course: "literature" },
    { typeOfCollege: "arts", course: "history" },
    { typeOfCollege: "arts", course: "philosophy" },
    { typeOfCollege: "arts", course: "linguistics" },
    { typeOfCollege: "arts", course: "fine arts" },
    { typeOfCollege: "arts", course: "music" },
    { typeOfCollege: "arts", course: "theater" },
    { typeOfCollege: "arts", course: "film studies" },
    { typeOfCollege: "science", course: "psychology" },
    { typeOfCollege: "science", course: "sociology" },
    { typeOfCollege: "science", course: "political science" },
    { typeOfCollege: "science", course: "anthropology" },
    { typeOfCollege: "science", course: "international relations" },
    { typeOfCollege: "science", course: "criminology" },
    { typeOfCollege: "medical", course: "medicine" },
    { typeOfCollege: "medical", course: "nursing" },
    { typeOfCollege: "medical", course: "pharmacy" },
    { typeOfCollege: "medical", course: "dentistry" },
    { typeOfCollege: "medical", course: "physiotherapy" },
    { typeOfCollege: "medical", course: "veterinary science" },
    { typeOfCollege: "medical", course: "public health" },
    { typeOfCollege: "medical", course: "nutrition & dietetics" },
    { typeOfCollege: "law", course: "law" },
    { typeOfCollege: "law", course: "criminal justice" },
    { typeOfCollege: "law", course: "international law" },
    { typeOfCollege: "law", course: "corporate law" },
    { typeOfCollege: "arts", course: "primary education" },
    { typeOfCollege: "arts", course: "secondary education" },
    { typeOfCollege: "arts", course: "special education" },
    { typeOfCollege: "arts", course: "educational psychology" },
    { typeOfCollege: "science", course: "agricultural science" },
    { typeOfCollege: "science", course: "horticulture" },
    { typeOfCollege: "science", course: "forestry" },
    { typeOfCollege: "science", course: "sustainable development" },
    { typeOfCollege: "arts", course: "journalism" },
    { typeOfCollege: "arts", course: "mass communication" },
    { typeOfCollege: "arts", course: "public relations" },
    { typeOfCollege: "arts", course: "advertising" }
  ];
  